## 간단한 인공신경망 만들기

In [8]:
import torch
from torch import nn

x=torch.tensor([1.])
model=nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦
print(model)

print(model.weight) # 만들면서 initialize 함
print(model.bias)

y=model(x)
print(y)

y2= x@model.weight + model.bias # 식으로 나타내 본다면..
print(y2)

Linear(in_features=1, out_features=1, bias=True)
Parameter containing:
tensor([[-0.6355]], requires_grad=True)
Parameter containing:
tensor([0.7252], requires_grad=True)
tensor([0.0896], grad_fn=<ViewBackward0>)
tensor([0.0896], grad_fn=<AddBackward0>)


In [18]:
fc1 = nn.Linear(1,3) # fully-connected
fc2 = nn.Linear(3,1)
"""
print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)
"""

x=torch.tensor([1.])
x=fc1(x)
print(x)
y=fc2(x)
print(y)

x = torch.tensor([1.])
y2 = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
print(y2)

tensor([-0.0425,  1.7186,  0.6195], grad_fn=<ViewBackward0>)
tensor([-0.3117], grad_fn=<ViewBackward0>)
tensor([-0.3117], grad_fn=<AddBackward0>)


In [21]:
model = nn.Linear(2,3)
x = torch.randn(2)
print(x)
print(model(x))
## nn.Linear는 데이터의 shape의 마지막 차원이 '채'로(1D data) 들어오길 기대하는 녀석이다.
# (입력 노드 하나가 곧 하나의 채널(피쳐) 값을 의미)
# ('채널'은 'TV 채널'의 '채널' 같이 특정 유형의 정보를 전달하는 통로. 즉, 피쳐(특징)와 의미적으로 거의 비슷함)

tensor([-1.1350,  0.1577])
tensor([ 0.4034, -0.3980,  1.0344], grad_fn=<ViewBackward0>)


In [24]:
model = nn.Linear(2,3)
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채의 형태로 줘야 함('채x개'나 '개x채' 이런 식으로 말고!)
x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개

print(x)
print(model(x))

x=torch.randn(4,5,2) #nn.Linear는 이거를 개x개x채로 들어왔다고 판단
print(model(x).shape)

x=torch.randn(2,3,6,4,5,2)
print(model(x).shape)

tensor([[ 1.1263,  0.0185],
        [ 0.0478,  1.0502],
        [ 1.4197, -0.6013],
        [ 0.8364, -2.2022],
        [-0.4198,  1.1690]])
tensor([[-0.6285, -0.3194, -0.3033],
        [ 0.0440, -0.3454, -0.0703],
        [-0.9389, -0.3472, -0.4643],
        [-1.3857, -0.5832, -0.9594],
        [ 0.2123, -0.3904, -0.0638]], grad_fn=<AddmmBackward0>)
torch.Size([4, 5, 3])
torch.Size([2, 3, 6, 4, 5, 3])


In [27]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

model = nn.Sequential(fc1,fc2)
x=torch.tensor([1.])
print(model(x))

tensor([-0.1580, -1.4860,  0.4340], grad_fn=<ViewBackward0>)
tensor([0.0623], grad_fn=<ViewBackward0>)
tensor([0.0623], grad_fn=<ViewBackward0>)


In [28]:
model = nn.Sequential(nn.Linear(2,5), # (in_채널, out_채널)이니까 연결되는 부분이 같아야 함
                      nn.Linear(5,10),
                      nn.Linear(10,3))
x=torch.randn(5,2) # 2개의 채널을 가지는 5개의 데이
print(x)
print(model(x))

tensor([[ 1.6837, -0.7941],
        [ 0.1860,  1.6101],
        [ 1.2975,  1.9257],
        [ 1.0924, -1.3953],
        [ 0.0107,  1.3729]])
tensor([[-0.0816, -0.3274,  0.5937],
        [-0.4258, -0.3646,  0.2629],
        [-0.5780, -0.2407,  0.1980],
        [ 0.0835, -0.4132,  0.6923],
        [-0.3654, -0.3927,  0.3008]], grad_fn=<AddmmBackward0>)


In [29]:
class MyModel(nn.Module):
  def __init__(self):
      super().__init__()

      self.fc1 = nn.Linear(2,5)
      self.fc2 = nn.Linear(5,10)
      self.fc3 = nn.Linear(10,3)
      self.act = nn.Sigmoid()

  def forward(self, x):
    x = self.fc1(x)
    x = self.act(x)
    x = self.fc2(x)
    x = self.act(x)
    x = self.fc3(x)
    x = self.act(x)
    return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.3810, 0.5116, 0.5377],
        [0.3812, 0.5122, 0.5373],
        [0.3811, 0.5119, 0.5374],
        [0.3798, 0.5079, 0.5413],
        [0.3807, 0.5114, 0.5380]], grad_fn=<SigmoidBackward0>)


In [30]:
print(model)
print(model.fc1.weight)
print(model.fc2.bias)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (act): Sigmoid()
)
Parameter containing:
tensor([[-0.0298,  0.1644],
        [-0.7033, -0.2561],
        [ 0.7017, -0.0821],
        [-0.5535,  0.6711],
        [-0.1822, -0.5736]], requires_grad=True)
Parameter containing:
tensor([ 0.0590, -0.0997, -0.3303, -0.2387,  0.3552,  0.0242,  0.4090, -0.3490,
         0.1522,  0.2507], requires_grad=True)


In [32]:
class MyModel2(nn.Module):
  def __init__(self):
    super().__init__()

    self.linear = nn.Sequential(nn.Linear(2,5),
                                nn.Sigmoid(),
                                nn.Linear(5,10),
                                nn.Sigmoid(),
                                nn.Linear(10,3),
                                nn.Sigmoid())

  def forward(self, x):
    x = self.linear(x)
    return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model2(x)
print(y)

tensor([[0.5402, 0.5121, 0.3686],
        [0.5409, 0.5114, 0.3676],
        [0.5463, 0.5082, 0.3670],
        [0.5415, 0.5112, 0.3680],
        [0.5414, 0.5116, 0.3695]], grad_fn=<SigmoidBackward0>)


In [35]:
print(model2)
print(model2.linear[0].weight)
print(model2.linear[-2].bias)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[-0.4705, -0.1990],
        [ 0.5610,  0.3923],
        [ 0.6481, -0.0798],
        [ 0.0126, -0.6472],
        [-0.1066, -0.0709]], requires_grad=True)
Parameter containing:
tensor([-0.0540,  0.0525, -0.2543], requires_grad=True)


In [36]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0298,  0.1644],
         [-0.7033, -0.2561],
         [ 0.7017, -0.0821],
         [-0.5535,  0.6711],
         [-0.1822, -0.5736]], requires_grad=True),
 Parameter containing:
 tensor([0.4474, 0.1405, 0.4438, 0.4377, 0.4937], requires_grad=True),
 Parameter containing:
 tensor([[-0.3138,  0.0269, -0.3689, -0.3510, -0.4393],
         [-0.2636,  0.0213, -0.2736, -0.3635, -0.1570],
         [-0.0537,  0.0206, -0.2458, -0.0861, -0.3705],
         [ 0.1341,  0.3889,  0.4386, -0.1444,  0.1182],
         [ 0.4337,  0.3423, -0.1150,  0.1385,  0.0180],
         [-0.1208,  0.0801,  0.2338, -0.2637, -0.2402],
         [-0.2951,  0.1001, -0.0678, -0.0836, -0.1882],
         [ 0.1348, -0.0837, -0.3120, -0.1591, -0.1958],
         [-0.4104,  0.2257, -0.4146, -0.2774, -0.4071],
         [-0.2502,  0.2755,  0.3059,  0.1968, -0.0752]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0590, -0.0997, -0.3303, -0.2387,  0.3552,  0.0242,  0.4090, -0.3490,
       

In [37]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108
