## pytorch의 여러 함수들

In [2]:
import torch
A=torch.randn(3,3) # Normal의 n
B=torch.rand(3,3) # 이건 uniform
print(A)
print(B)

tensor([[ 0.5910, -0.3941,  2.1592],
        [-2.2214, -0.5378, -0.0987],
        [-0.0584, -0.5756, -2.3267]])
tensor([[0.4735, 0.7915, 0.5021],
        [0.2150, 0.6552, 0.7331],
        [0.9446, 0.1125, 0.9754]])


In [12]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) #torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A,decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-0.3299, -0.3710, -0.5799],
        [-1.1479, -0.2503,  2.4098],
        [ 0.2846,  0.3883, -0.2061]])
tensor([[0.3299, 0.3710, 0.5799],
        [1.1479, 0.2503, 2.4098],
        [0.2846, 0.3883, 0.2061]])
tensor([[0.5744, 0.6091, 0.7615],
        [1.0714, 0.5003, 1.5523],
        [0.5335, 0.6232, 0.4540]])
tensor([[ 0.7190,  0.6900,  0.5599],
        [ 0.3173,  0.7786, 11.1314],
        [ 1.3293,  1.4745,  0.8137]])
tensor([[-1.1089, -0.9915, -0.5448],
        [ 0.1380, -1.3850,  0.8795],
        [-1.2565, -0.9459, -1.5793]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[-0., -0., -1.],
        [-1., -0.,  2.],
        [ 0.,  0., -0.]])
tensor([[-0.3300, -0.3700, -0.5800],
        [-1.1500, -0.2500,  2.4100],
        [ 0.2800,  0.3900, -0.2100]])
tensor([[-1., -1., -1.],
        [-2., -1.,  2.],
        [ 0.,  0., -1.]])
tensor([[-0., -0., -0.],
        [-1., -0.,  3.],
        [ 1.,  1., -0.]])


In [13]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)


torch.Tensor

In [17]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [32]:
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0))
print(torch.max(A,dim=1))
print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A))
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[-1.1538, -1.0885,  0.9943, -1.9872],
        [ 0.8381, -1.7978, -0.6919, -0.9166],
        [-0.3482, -1.4777, -0.0706,  2.0760]])
tensor(2.0760)
torch.return_types.max(
values=tensor([ 0.8381, -1.0885,  0.9943,  2.0760]),
indices=tensor([1, 0, 0, 2]))
torch.return_types.max(
values=tensor([0.9943, 0.8381, 2.0760]),
indices=tensor([2, 0, 3]))
torch.return_types.max(
values=tensor([[ 0.8381, -1.0885,  0.9943,  2.0760]]),
indices=tensor([[1, 0, 0, 2]]))
torch.return_types.max(
values=tensor([[0.9943],
        [0.8381],
        [2.0760]]),
indices=tensor([[2],
        [0],
        [3]]))
torch.return_types.min(
values=tensor([-1.1538, -1.7978, -0.6919, -1.9872]),
indices=tensor([0, 1, 1, 0]))
torch.return_types.min(
values=tensor([-1.9872, -1.7978, -1.4777]),
indices=tensor([3, 1, 1]))
tensor(11)
tensor([1, 0, 0, 2])
tensor([2, 0, 3])


In [37]:
a = torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted)

a=torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[-0.9294],
        [-0.9247],
        [ 1.0041],
        [-0.6959],
        [-1.3397],
        [ 0.3180]])
torch.return_types.sort(
values=tensor([[-1.3397],
        [-0.9294],
        [-0.9247],
        [-0.6959],
        [ 0.3180],
        [ 1.0041]]),
indices=tensor([[4],
        [0],
        [1],
        [3],
        [5],
        [2]]))
tensor([[-0.2183],
        [ 0.0819],
        [ 0.5626],
        [-0.8123],
        [-0.9496],
        [-1.3570]])
torch.return_types.sort(
values=tensor([[-1.3570],
        [-0.9496],
        [-0.8123],
        [-0.2183],
        [ 0.0819],
        [ 0.5626]]),
indices=tensor([[5],
        [4],
        [3],
        [0],
        [1],
        [2]]))
torch.return_types.sort(
values=tensor([[ 0.5626],
        [ 0.0819],
        [-0.2183],
        [-0.8123],
        [-0.9496],
        [-1.3570]]),
indices=tensor([[2],
        [1],
        [0],
        [3],
        [4],
        [5]]))
tensor(0.5626)
tensor(0.5626)
tensor([[0.2183],
        [0.081

In [42]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차
print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[ 0.2685,  0.6577, -1.5920, -1.0083],
        [ 0.0849,  0.2832, -0.5456, -0.1676],
        [ 0.4668, -0.7181, -1.9943, -1.1485]])
tensor(-5.4133)
tensor([-1.6742, -0.3450, -3.3941])
tensor([[-1.6742],
        [-0.3450],
        [-3.3941]])
tensor(-0.4511)
tensor([-0.4185, -0.0863, -0.8485])
tensor([[-0.4185],
        [-0.0863],
        [-0.8485]])
tensor(0.8558)
tensor([[-1.6742],
        [-0.3450],
        [-3.3941]])
tensor([[-0.4185],
        [-0.0863],
        [-0.8485]])
tensor(0.8558)


In [45]:
A=torch.randint(1,5,size=(12,))
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim)

tensor([3, 3, 2, 1, 3, 1, 1, 1, 3, 1, 3, 4])
torch.Size([12])
tensor([[[3, 3, 2],
         [1, 3, 1]],

        [[1, 1, 3],
         [1, 3, 4]]])
3


In [53]:
A=torch.arange(20,)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 되도록 열의 수를 맞춰준다!
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2 차원 행 벡터
print(A.reshape(-1,1).shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [64]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(1,2,0).shape)
print(A.transpose(2,1).shape)
print(A.transpose(1,2).shape)

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([3, 6, 4])
torch.Size([4, 6, 3])
torch.Size([4, 6, 3])


In [66]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)

torch.Size([4, 5, 6])


In [71]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
C=torch.vstack([A,B])
D=torch.hstack([A,B])
E=torch.cat([A,B],dim=0)
F=torch.cat([A,B],dim=1)
print(F)

tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [78]:
A=torch.randn(1,1,1,3,1,1,1,4,1,1,1)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(dim=(0,2,4,5)).shape)

torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])


In [89]:
A = torch.randn(3,4)
print(A)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

tensor([[ 0.8127, -1.2238, -0.2967, -0.2984],
        [ 0.8551,  0.0790,  0.0600,  0.0857],
        [ 0.2904, -2.5049, -2.3006,  0.7772]])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [99]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B],dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [100]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
C=torch.stack([A,B])
print(C) # unsqueeze 안하고 stack으로 하면 되긴함. (차원을 추가(default는 dim=0에)해서 쌓아줌)
# 근데 차원을 추가해서 쌓는 방식이다보니 A,B shape이 완전히 일치해야함. concat은 달라도 쌓을 차원 이외 차원들만 맞으면 됨

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [106]:
import torch
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0] = 100
print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @에 대해 설명

In [109]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [111]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

torch.Size([32, 5, 10])


## numpy<->torch 왔다갔다 기능

In [112]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a)
B=b.numpy()
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
