In [2]:
import torch
a=torch.tensor([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
b=torch.tensor([1,2,3.1,4])
print(b.type) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
<built-in method type of Tensor object at 0x7c75c2003410>
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [4]:
A=torch.tensor([[1,2,3],[3,4,5]])# 이 셀부터는 import torch는 실행했다 치고 작성
# A=torch.tensor([[1,2], [3,4,5] ]) #리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim)
print(A.numel()) #전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [5]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [6]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [9]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셉은? 성분끼리 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [10]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])
