In [1]:
import torch
# 3차원 행렬 인덱싱
A=torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(A)
print(A.shape)
print(A[0,1,2])
a=torch.tensor([[[[[1,2,3,4]]]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 1, 1, 4])


In [2]:
# 리스트로 인덱싱
print(A)
A[[0,1,1,0],[0,1,2,1],[3,3,2,1]]

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([ 3, 19, 22,  5])

In [8]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A>3) # 리스트와 달리 각 성분에 대해 비교해 줌
print(A[A>3]) # True, False가 담긴 행렬로 인덱싱 가능!
A[A>3]=100
print(A) # 그러면 어떤 것도 가능하다!(3보다 큰 애들은 100으로 바꿔줘)
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False, False,  True],
        [ True, False,  True, False]])
tensor([4, 5, 7])
tensor([[  1,   2,   3, 100],
        [100,   3, 100,   3]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [18]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[torch.tensor(2)] # torch.tensor를 안에다가?
print(A)
A=a[torch.tensor([2,3,4])]
print(A)
A=a[torch.tensor([[2,2,2],[3,3,3]])]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다.
a=torch.tensor([1,2,3])
print(a[torch.tensor([[1,1,1],[2,2,2]])])
a=torch.tensor([[1,2,3],[4,5,6]])
print(a[torch.tensor(0)])
A=a[torch.tensor([[0,1],[1,1]])]
print(A)
print(A.shape)

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([[2, 2, 2],
        [3, 3, 3]])
tensor([1, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])


In [30]:
A=torch.tensor([[1,2,6],[3,4,7],[5,6,2],[7,8,9]])
print(A)
print()
#print(A.shape)
print()
# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
#print(A[0,1])
#print()
# 2-1. A[[몇 번째 행이냐, 몇 번째 행이냐],[몇 번째 열이냐, 몇 번째 열이냐]]
print(A[[0,2,3,1,2],[1,1,0,0,0]])
print()
# 2-2. A[[[몇 번째 행이냐], [몇 번째 행이냐]], [[몇 번째 열이냐], [몇 번째 열이냐]]] ==> 결과가 행렬형태가 되도록 인덱싱
print(A[[[0,2],[3,1]], [[0,2],[1,0]]])
print()
# 3. a[tensor(bool)] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[torch.tensor([[False,True,True],[False,False,False],[False,False,True],[False,True,False]])])
print()
print(A[A==2]) # 마스킹 같은 걸 할 수 있음
print()
# 4. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[[True,False,False,False],[False,True,True]])
print()
# 5. A[tensor] ==> 몇 번째 것을 어떻게 쌓을거냐
print(A[torch.tensor([1,1,2,2,2])])

tensor([[1, 2, 6],
        [3, 4, 7],
        [5, 6, 2],
        [7, 8, 9]])


tensor([2, 6, 7, 3, 5])

tensor([[1, 2],
        [8, 3]])

tensor([2, 6, 2, 8])

tensor([2, 2])

tensor([2, 6])

tensor([[3, 4, 7],
        [3, 4, 7],
        [5, 6, 2],
        [5, 6, 2],
        [5, 6, 2]])
